export let data = {
    "Order": ["NYT Mini Crossword", "AI Generated Mini Crossword", "Joley's Crossword", "Charlotte's Birthday Crossword", "Father's Day 2025"],
    "Father's Day 2025":  {
        title: "Father's Day Crossword",
        keyword: "f",
        solution : [
            "RAFAEL",
            "O*O**A",
            "DIR*D*",
            "GITHUB",
            "E*YEAR",
            "R**ELO",
            "*DEL*W",
            "RAZ**N",
            "*D****",
        ],
        across : {
            1: "Has never broken a racket in his career",
            4: "ls, on Windows",
            7: "Web Application where someone might fork",
            10: "Fiscal ___",
            11: "Jaden has 2000 of this in Rapid",
            12: "Keyword to free malloced memory in C++, abbr.",
            14: "__ kids, a terrible website"
        },
        down : {
            1: "Combination of 2 words: a Wimbledon Champion, a Racoon-like animal",
            2: "COMM's highest stock price, rounded to the tens",
            3: "Liga",
            5: "Two",
            6: "Consisting of two parts",
            8: "High __ boots",
            9: "2026 All NBA Second Team, at least",
            12: "What Padre means in Spanish",
            13: "Teenage slang for something easy",
        },
        message: "Happy Father's Day!",
    },
    "Joley's Crossword": {
        title: "Joley's Crossword",
        keyword: "j",
        solution: [
            "SNAKE",
            "EIGEN",
            "MANNY",
            "ONE*O",
            "NG*G*",
            "E*JOB",
            "GRAD*",
            "*BY**",
        ],
        across: {
            1: "Forgotten Adventure Time animal, made from a tie at College Gate College Academy camp",
            11: "Everyone in college is worried about this",
            6: "__vector",
            7: "Helped students cheat on the ACT",
            8: "Sum of states in a Markov Chain",
            9: "First 2 letters of Cantonese word for I (pinyin)",
            12: "Official spelling of eatybaby's first name",
            14: "Common word in a book cover"
        },
        down: {
            1: "[Spelled upside down] Complete set of genetic material in an organism",
            2: "娘 pinyin, as in 姑娘",
            13: "Rubidium",
            3: "Jennifer's last name. TGIF!",
            11: "Gadsby's first name",
            4: "Anywhere else he'd be a ten",
            10: "Adventures of __",
            5: "Goddess of war and destruction"
        },
        message: "What a Moley!",
    },
    "Charlotte's Birthday Crossword": {
        title: "Charlotte's Birthday Crossword",
        keyword: "c",
        solution: [
            "**MA*T",
            "**INGA",
            "**RYAN",
            "**A*MJ",
            "***PEI",
            "**LI*R",
            "ADAGIO",
            "CAI*O*",
            "T*TONG",
        ],
        across: {
            1: "BU IS IN __",
            4: "Keys For Kids Director",
            6: "Formerly a baby",
            7: "Zendaya played this character",
            8: "(Cantonese) Fong zho yaat dook __",
            9: "3rd element in periodic table",
            10: "Meaning to play the piece slowly",
            13: "(Mandarin) Bok Choy, Gai Lan, e.g.",
            14: "__ choy (it's hollow)"
        },
        down: {
            1: "Problem child",
            2: "__ day now",
            5: "Subway Surfers, The Battle Cats, e.g.",
            3: "Wears green and black",
            8: "Species of protagonist, in a book containing your name",
            9: "(French) Milk",
            10: "Has an English, Math, Science section",
            11: "Cool way of saying 'the'",
            12: "Unequal number of electrons and protons"
        },
        message: "Happy Birthday!",
    },
    "NYT Mini Crossword": {
        title: "NYT Mini Crossword",
        keyword: "mini"
    },
    "NYT Midi Crossword": {
        title: "NYT Midi Crossword",
        keyword: "midi"
    },
    "NYT Big Crossword": {
        title: "NYT Big Crossword",
        keyword: "big"
    },
    "AI Generated Mini Crossword": {
        title: "AI Generated Mini Crossword",
        keyword: "ai"
    },
    "Ally's STR Crossword":  {
        title: "Ally's STR Crossword",
        keyword: "a",
        solution : [
        "TO*PABULUM*ERR*S*V**",
        "W*BOW*NO*ALLTOOWELL*",
        "IDOL*E*KEG*BAR*A*EE*",
        "XRAY*XWING*A*YTTRIUM",
        "*O*PITH*TIL*A*A*I*NA",
        "*V**POOR*LIPCOMBO*GI",
        "CEPHALOFOIL*K**A***N",
        "O*IOS**AOC*U*GUNKY**",
        "WEPT*CS*PI*LLAMA*UCL",
        "*****AH**OPTIMAL*MRI",
        "LS*MICRO*U*ANG**AMOR",
        "YAPASAURUS**TEAMAYCE",
        "EBB*MOGS**HAYRES*A*S*"
        ],
        across : {
            1: "Two letter too",
            2: "Boring Mistake",
            7: "Mistake",
            12: "Movement of respect",
            13: "Yes op",
            14: "I'll remember it",
            16: "Hero",
            19: "College party equip.",
            21: "21st birthday destination",
            22: "Tech Major",
            23: "Black & White picture",
            24: "Rebel ship",
            26: "Diabolical hangman",
            30: "Fruit Tissue",
            32: "With 4 down, up to a time",
            35: "Not applicable, abbreb",
            36: "Rhymes with opp. of less",
            38: "Liner + stick + shine?",
            40: "Gut tract",
            41: "Hammerhead head",
            45: "Apple format",
            46: "NY 14th district rep",
            48: "Gooped up",
            51: "Cried",
            52: "Tech major",
            54: "March 14",
            55: "Spitting Animal",
            57: "What Tommy John surgery is for",
            60: "___ ha!",
            61: "Julian",
            62: "Med scan",
            63: "List Directory",
            65: "Macro opp.",
            68: "Flying guardsmen, USA abbrev.",
            69: "My love",
            70: "Big talker",
            72: "Best sushi table",
            74: '"____ and flow"',
            75: "Slays",
            76: "Ye olde shark" 
        },
        down : {
            1: "Chocolate Candy",
            2: "Abnormal growth",
            3: "Cute expression",
            4: "With 32 across, up to a time",
            5: "God of mischief",
            6: "Affectionate nickname, Tiernan",
            7: "Idris",
            8:" Regional transport grp. abbreb.",
            9: "The third Lorelei",
            10: "Fly down?",
            11: "Marsh",
            12: "Snake",
            15: "Jaden",
            17: "Drake and ___, past tense",
            18: "Praise",
            20: "Treebeard species",
            25: "Roller coaster exclamation",
            27: "Scottish hat",
            28: "2016 Olympics loc",
            29: "Branch you should never push to",
            31: "Bitter beers",
            33: "Itty bitty",
            34: "SYN-",
            37: "Tissue removal via heat",
            39: "Lacking originality",
            41: "Free Chick-fil-a dress",
            42: "Install key?",
            43: "Katy Perry 'you change your mind' song, first word",
            44: "Java language type",
            47: "Mid class Sephora",
            48: "Hero of LOTR, last name",
            49: "Thunderman",
            50: "Justin Bieber song, repetitive",
            52: "Chocolate Source",
            53: "Idk? Movement",
            56: "Describe clothes that need a roller",
            58: "Eli shoes of choice",
            59: "Old Italian currency, plural",
            63: "Soup ingred",
            64: "NYC Ballet VIP",
            65: "Mass, abbrev.",
            66: "Suffix, belief system to noun",
            67: "Ands op?",
            69: "Highway shoulder call",
            71: "___ and j",
            73: "Clueless \"___ if!\""

        },
        message: "Happy Father's Day!",
        groupedClues: [["4D", "32A"]],
    },
    // BASE_URL: "http://127.0.0.1:5001/crossword",
    BASE_URL: "https://crossword-fua4bdbycsgrfwfp.eastus-01.azurewebsites.net/crossword",
    urls: {
        MINI_CROSSWORD_URL: "/mini",
        MIDI_CROSSWORD_URL: "/midi",
        BIG_CROSSWORD_URL: "/big",
        AI_URL: "https://monkey2.azurewebsites.net/gen",
    }
};