export let data = {
    "Order": ["NYT Mini Crossword", "AI Generated Mini Crossword", "Joley's Crossword", "Charlotte's Birthday Crossword", "Father's Day 2025"],
    "Father's Day 2025":  {
        title: "Father's Day Crossword",
        keyword: "f",
        solution : [
            "RAFAEL",
            "O*O**A",
            "DIR*D*",
            "GITHUB",
            "E*YEAR",
            "R**ELO",
            "*DEL*W",
            "RAZ**N",
            "*D****",
        ],
        across : {
            1: "Has never broken a racket in his career",
            4: "ls, on Windows",
            7: "Web Application where someone might fork",
            10: "Fiscal ___",
            11: "Jaden has 2000 of this in Rapid",
            12: "Keyword to free malloced memory in C++, abbr.",
            14: "__ kids, a terrible website"
        },
        down : {
            1: "Combination of 2 words: a Wimbledon Champion, a Racoon-like animal",
            2: "COMM's highest stock price, rounded to the tens",
            3: "Liga",
            5: "Two",
            6: "Consisting of two parts",
            8: "High __ boots",
            9: "2026 All NBA Second Team, at least",
            12: "What Padre means in Spanish",
            13: "Teenage slang for something easy",
        },
        message: "Happy Father's Day!",
    },
    "Joley's Crossword": {
        title: "Joley's Crossword",
        keyword: "j",
        solution: [
            "SNAKE",
            "EIGEN",
            "MANNY",
            "ONE*O",
            "NG*G*",
            "E*JOB",
            "GRAD*",
            "*BY**",
        ],
        across: {
            1: "Forgotten Adventure Time animal, made from a tie at College Gate College Academy camp",
            11: "Everyone in college is worried about this",
            6: "__vector",
            7: "Helped students cheat on the ACT",
            8: "Sum of states in a Markov Chain",
            9: "First 2 letters of Cantonese word for I (pinyin)",
            12: "Official spelling of eatybaby's first name",
            14: "Common word in a book cover"
        },
        down: {
            1: "[Spelled upside down] Complete set of genetic material in an organism",
            2: "娘 pinyin, as in 姑娘",
            13: "Rubidium",
            3: "Jennifer's last name. TGIF!",
            11: "Gadsby's first name",
            4: "Anywhere else he'd be a ten",
            10: "Adventures of __",
            5: "Goddess of war and destruction"
        },
        message: "What a Moley!",
    },
    "Charlotte's Birthday Crossword": {
        title: "Charlotte's Birthday Crossword",
        keyword: "c",
        solution: [
            "**MA*T",
            "**INGA",
            "**RYAN",
            "**A*MJ",
            "***PEI",
            "**LI*R",
            "ADAGIO",
            "CAI*O*",
            "T*TONG",
        ],
        across: {
            1: "BU IS IN __",
            4: "Keys For Kids Director",
            6: "Formerly a baby",
            7: "Zendaya played this character",
            8: "(Cantonese) Fong zho yaat dook __",
            9: "3rd element in periodic table",
            10: "Meaning to play the piece slowly",
            13: "(Mandarin) Bok Choy, Gai Lan, e.g.",
            14: "__ choy (it's hollow)"
        },
        down: {
            1: "Problem child",
            2: "__ day now",
            5: "Subway Surfers, The Battle Cats, e.g.",
            3: "Wears green and black",
            8: "Species of protagonist, in a book containing your name",
            9: "(French) Milk",
            10: "Has an English, Math, Science section",
            11: "Cool way of saying 'the'",
            12: "Unequal number of electrons and protons"
        },
        message: "Happy Birthday!",
    },
    "NYT Mini Crossword": {
        title: "NYT Mini Crossword",
        keyword: "n"
    },
    "AI Generated Mini Crossword": {
        title: "AI Generated Mini Crossword",
        keyword: "a"
    },
    CROSSWORD_URL: "https://crossword-fua4bdbycsgrfwfp.eastus-01.azurewebsites.net/crossword",
    AI_URL: "https://monkey2.azurewebsites.net/gen",
};